### ISSUE TITLE
1st monthly report of LEMP

### ISSUE THREAD

**Issue by yjko2** [moja-global/LEMP.GCBM.Environmentally_sensitive_forest_module#1]
This is my first monthly report of LEMP. 
I upload my work plan for first month in google doc because I didn't upload it here. 

I share my first report through [docs.](https://docs.google.com/document/d/1h1X0Pjh7UMFa0o2f8yH1PgpRsOc0LeVXM2Smy5wTAPA/edit?usp=sharing)

I have a question. How I upload shp file on github? 
I made some shp file about my study area. 

Please check and review it. 
Thank you for your consideration.
@gmajan @mfellows @saloni-garg

**Comment by gmajan** [comment]
Hi @yjko2 
thank you for the report. 
Most repos in moja global have a science folder and a code folder. Where applicable there is also a data folder. So in your particular situation, I would suggest to turn your report into a pdf when it is final and [upload it in the science folder](https://docs.github.com/en/github/managing-files-in-a-repository/adding-a-file-to-a-repository). 
Data can be uploaded in a similar way in the data folder.
Does this help? Just let us know. Thx.
